const LIVE_TRADE_CONFIG = [
  {
    displayName: "Adani Enterprises",
    exchangeType: "NSE",
    scripId: 25,
    symbol: "ADANIENT",
    scripType: "EQUITY",
  },
  {
    scripId: 3563,
    symbol: "ADANIGREEN",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Adani Green Energy",
  },
  {
    scripId: 14366,
    symbol: "IDEA",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Vodafone Idea",
  },
  {
    scripId: 24777,
    symbol: "OLAELEC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "OLA Electric Mobility",
  },
  {
    scripId: 11915,
    symbol: "YESBANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Yes Bank",
  },
  {
    scripId: 11763,
    symbol: "JPPOWER",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Jaiprakash Power Ventures",
  },
  {
    scripId: 12018,
    symbol: "SUZLON",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Suzlon",
  },
  {
    scripId: 13745,
    symbol: "GTLINFRA",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "GTL Infra.Ltd",
  },
  {
    scripId: 29124,
    symbol: "PCJEWELLER",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Pc Jeweller Ltd",
  },
  {
    scripId: 15259,
    symbol: "RPOWER",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Reliance Power",
  },
  {
    scripId: 5097,
    symbol: "ETERNAL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Eternal (formerly Zomato)",
  },
  {
    scripId: 17520,
    symbol: "RTNPOWER",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Rattanindia Power",
  },
  {
    scripId: 27052,
    symbol: "SAGILITY",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Sagility",
  },
  {
    scripId: 759806,
    symbol: "GROWW",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Groww - Billionbrains Garage Ventures",
  },
  {
    scripId: 11184,
    symbol: "IDFCFIRSTB",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "IDFC First Bank",
  },
  {
    scripId: 3499,
    symbol: "TATASTEEL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Tata Steel",
  },
  {
    scripId: 17388,
    symbol: "ADANIPOWER",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Adani Power",
  },
  {
    scripId: 10794,
    symbol: "CANBK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Canara Bank",
  },
  {
    scripId: 2792,
    symbol: "EASEMYTRIP",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Easy Trip Planners",
  },
  {
    scripId: 21951,
    symbol: "HFCL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "HFCL",
  },
  {
    scripId: 1333,
    symbol: "HDFCBANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "HDFC Bank",
  },
  {
    scripId: 27969,
    symbol: "VMM",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Vishal Mega Mart",
  },
  {
    scripId: 15332,
    symbol: "NMDC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "NMDC",
  },
  {
    scripId: 1375,
    symbol: "HCC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Hindustan Construction Company",
  },
  {
    scripId: 5948,
    symbol: "SOUTHBANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "South Indian Bank",
  },
  {
    scripId: 1491,
    symbol: "IFCI",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "IFCI",
  },
  {
    scripId: 2963,
    symbol: "SAIL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Steel Authority Of India",
  },
  {
    scripId: 10666,
    symbol: "PNB",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Punjab National Bank",
  },
  {
    scripId: 1660,
    symbol: "ITC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "ITC",
  },
  {
    scripId: 11377,
    symbol: "MAHABANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bank of Maharashtra",
  },
  {
    scripId: 30125,
    symbol: "SAMMAANCAP",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Sammaan Capital",
  },
  {
    scripId: 2331,
    symbol: "JAYNECOIND",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Jayaswal Neco Industr",
  },
  {
    scripId: 15308,
    symbol: "SEPC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Shriram Epc",
  },
  {
    scripId: 383,
    symbol: "BEL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bharat Electronics",
  },
  {
    scripId: 212,
    symbol: "ASHOKLEY",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Ashok Leyland",
  },
  {
    scripId: 17939,
    symbol: "HINDCOPPER",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Hindustan Copper",
  },
  {
    scripId: 3063,
    symbol: "VEDL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Vedanta",
  },
  {
    scripId: 13528,
    symbol: "GMRAIRPORT",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "GMR Airports Infrastructure",
  },
  {
    scripId: 10300,
    symbol: "RAMASTEEL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Rama Steel Tubes",
  },
  {
    scripId: 1607,
    symbol: "AURIGROW",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Godha Cabcon Insulat Ltd",
  },
  {
    scripId: 1476,
    symbol: "IDBI",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "IDBI Bank",
  },
  {
    scripId: 18143,
    symbol: "JIOFIN",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Jio Financial Services",
  },
  {
    scripId: 10753,
    symbol: "UNIONBANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Union Bank Of India",
  },
  {
    scripId: 1624,
    symbol: "IOC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Indian Oil Corp",
  },
  {
    scripId: 2029,
    symbol: "IRFC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "IRFC",
  },
  {
    scripId: 2475,
    symbol: "ONGC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "ONGC",
  },
  {
    scripId: 760726,
    symbol: "BHARATCOAL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bharat Coking Coal",
  },
  {
    scripId: 17400,
    symbol: "NHPC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Nhpc",
  },
  {
    scripId: 3787,
    symbol: "WIPRO",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Wipro",
  },
  {
    scripId: 15228,
    symbol: "UJJIVANSFB",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Ujjivan Small Finance Bank",
  },
  {
    scripId: 27066,
    symbol: "SWIGGY",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Swiggy Limited",
  },
  {
    scripId: 21794,
    symbol: "DAVANGERE",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Davangere Sugar Company",
  },
  {
    scripId: 2885,
    symbol: "RELIANCE",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Reliance Industries",
  },
  {
    scripId: 4963,
    symbol: "ICICIBANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "ICICI Bank",
  },
  {
    scripId: 15313,
    symbol: "IRB",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "IRB Infra",
  },
  {
    scripId: 760229,
    symbol: "MEESHO",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "MEESHO LIMITED",
  },
  {
    scripId: 14977,
    symbol: "POWERGRID",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Power Grid",
  },
  {
    scripId: 16249,
    symbol: "CCAVENUE",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "AvenuesAI Limited",
  },
  {
    scripId: 3045,
    symbol: "SBIN",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "State Bank Of India",
  },
  {
    scripId: 220,
    symbol: "IEX",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Indian Energy Exchange",
  },
  {
    scripId: 17888,
    symbol: "GATECH",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "GACM Technologies",
  },
  {
    scripId: 6364,
    symbol: "NATIONALUM",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "National Aluminium Co.Ltd",
  },
  {
    scripId: 3456,
    symbol: "TMPV",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Tata Motors Passenger Vehicles",
  },
  {
    scripId: 438,
    symbol: "BHEL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "BHEL",
  },
  {
    scripId: 3812,
    symbol: "ZEEL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Zee Entertainment",
  },
  {
    scripId: 31415,
    symbol: "NBCC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "NBCC",
  },
  {
    scripId: 4717,
    symbol: "GAIL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "GAIL",
  },
  {
    scripId: 11630,
    symbol: "NTPC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "NTPC",
  },
  {
    scripId: 757102,
    symbol: "BELRISE",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Belrise Industries",
  },
  {
    scripId: 6792,
    symbol: "SBC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "SBC Exports Limited",
  },
  {
    scripId: 1134,
    symbol: "APOLLO",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Apollo Micro Systems",
  },
  {
    scripId: 17675,
    symbol: "ALOKINDS",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Alok Industries",
  },
  {
    scripId: 1802,
    symbol: "JYOTISTRUC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Jyoti Structures Ltd",
  },
  {
    scripId: 21362,
    symbol: "SALASAR",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Salasar Techno Engg.",
  },
  {
    scripId: 4745,
    symbol: "BANKINDIA",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bank Of India",
  },
  {
    scripId: 7852,
    symbol: "INOXWIND",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Inox Wind",
  },
  {
    scripId: 1594,
    symbol: "INFY",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Infosys",
  },
  {
    scripId: 4668,
    symbol: "BANKBARODA",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bank Of Baroda",
  },
  {
    scripId: 759723,
    symbol: "PWL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "PHYSICSWALLAH LIMITED",
  },
  {
    scripId: 11223,
    symbol: "UCOBANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "UCO Bank",
  },
  {
    scripId: 20261,
    symbol: "IREDA",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Indian Renewable Energy",
  },
  {
    scripId: 2263,
    symbol: "BANDHANBNK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bandhan Bank",
  },
  {
    scripId: 2283,
    symbol: "MRPL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "MRPL",
  },
  {
    scripId: 9685,
    symbol: "TRIDENT",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Trident",
  },
  {
    scripId: 18391,
    symbol: "RBLBANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "RBL Bank",
  },
  {
    scripId: 1922,
    symbol: "KOTAKBANK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Kotak Bank",
  },
  {
    scripId: 25468,
    symbol: "PAISALO",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Paisalo Digital",
  },
  {
    scripId: 1023,
    symbol: "FEDERALBNK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Federal Bank",
  },
  {
    scripId: 27176,
    symbol: "NTPCGREEN",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "NTPC Green Energy",
  },
  {
    scripId: 18520,
    symbol: "CUPID",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Cupid",
  },
  {
    scripId: 9348,
    symbol: "IOB",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Indian Overseas Bank",
  },
  {
    scripId: 14894,
    symbol: "CENTRALBK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Central Bank Of India",
  },
  {
    scripId: 526,
    symbol: "BPCL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bharat Petroleum",
  },
  {
    scripId: 30108,
    symbol: "ABFRL",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Aditya Birla Fashion",
  },
  {
    scripId: 1424,
    symbol: "HINDZINC",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Hindustan Zinc",
  },
  {
    scripId: 308,
    symbol: "BAJAJHIND",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bajaj Hindusthan Sugar",
  },
  {
    scripId: 8833,
    symbol: "BCG",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Brightcom Group",
  },
  {
    scripId: 17358,
    symbol: "UTKARSHBNK",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Utkarsh Small Finance Bank",
  },
  {
    scripId: 20374,
    symbol: "COALINDIA",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Coal India",
  },
  {
    scripId: 317,
    symbol: "BAJFINANCE",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Bajaj Finance",
  },
  {
    scripId: 8596,
    symbol: "MSUMI",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Motherson Sumi Wiring",
  },
  {
    scripId: 9741,
    symbol: "PARADEEP",
    exchangeType: "NSE",
    scripType: "EQUITY",
    displayName: "Paradeep Phosphates",
  },
];

export default LIVE_TRADE_CONFIG;
